---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: instalando dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ collective_packages }}"

- name: clonando proyecto
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ collective_path }}"

- name: creando directorio tmp
  ansible.builtin.file:
    path: "{{ collective_path }}/app/tmp"
    state: directory

- name: cambiando permisos directorio collective
  ansible.builtin.file:
    path: "{{ collective_path }}"
    state: directory
    recurse: yes
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'

- name: copiando archivos de configuración
  ansible.builtin.template:
    src: "files/{{ collective_config }}.j2"
    dest: "{{ collective_path  }}/{{ collective_config }}"
  notify: reiniciar_apache   