---
- name: reiniciar_apache
  service:
    name: apache2
    enabled: yes
    state: restarted    
  
# - name: ufw_allow
#   ufw:
#     rule: allow
#     port: "{{ item }}"
#     proto: tcp
#   with_items:
#     - "{{ http_port }}"
#     - "{{ https_port }}"