---
- include_vars: ../../vars_main.yml

- name: Instalando mariadb
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ mariadb_packages }}"

- name: configurando password para root
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: eliminando acceso anonimo
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: eliminando la base de datos "test"
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true

- name: creando la base de datos "{{ mysql_db }}"
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true

- name: creando el usuario "{{ mysql_user }}"
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: localhost
    state: present
    update_password: on_create
    priv: "{{ mysql_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    