---
apache_packages: [ 'apache2', 'php' ]
php_packages: [ 'libapache2-mod-php7.4', 'php7.4-mbstring', 'php7.4-xmlrpc', 'php7.4-gd', 'php7.4-xml', 'php7.4-intl', 'php7.4-mysql', 'php7.4-cli', 'php7.4-zip', 'php7.4-curl', 'php7.4-posix', 'php7.4-dev', 'php7.4-redis', 'php7.4-gmagick', 'php7.4-gmp' ]